### ISSUE TITLE
Como paciente me gustaria poder registrarme "Login" en la plataforma

### ISSUE THREAD

**Issue by dalirod** [Johndbm/proyecto-final#14]
- [x] boton login en el navbar que redirija a una vista de registro y/o vista de inicio de sesion
- [x] Crear vista de login
- [x] Crear vista de registro
- [x] Crear formulario de registro en la vista login

**Comment by Johndbm** [comment]
conciliando conflicto entre archivos

**Comment by Johndbm** [comment]
Con la actualizacion del navbar, la vista de Login, ya no es necesaria
